# Generated by Django 4.0.2 on 2022-02-23 07:08

import author.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_author_is_active_alter_author_is_superuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='author',
            managers=[
                ('objects', author.models.MyUserManager()),
            ],
        ),
    ]
