# Generated by Django 4.0.2 on 2022-02-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_author_is_staff_alter_author_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
