# Generated by Django 4.0.2 on 2022-02-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0005_author_is_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='is_supervisor',
        ),
        migrations.AlterField(
            model_name='author',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
