# Generated by Django 4.0.2 on 2022-02-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.IntegerField(choices=[(0, 'Plain Text'), (1, 'Common Mark'), (2, 'Image Link'), (3, 'Image File')], default=0),
        ),
    ]
