# Generated by Django 4.0.2 on 2022-02-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.IntegerField(choices=[(0, 'Public'), (1, 'Friends'), (2, 'Private')], default=0),
        ),
    ]
