# Generated by Django 4.0.2 on 2022-03-03 01:34

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), default=0, max_length=66, size=6),
        ),
        migrations.AddField(
            model_name='post',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default='title'),
        ),
        migrations.AddField(
            model_name='post',
            name='unlisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
