# Generated by Django 4.0.2 on 2022-03-03 16:53

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_categories_post_count_post_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, null=True, size=6),
        ),
    ]
