# Generated by Django 4.0.3 on 2022-03-04 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='count',
        ),
    ]
