# Generated by Django 4.0.3 on 2022-03-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0004_alter_like_author_alter_like_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='summary',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
