# Generated by Django 4.0.2 on 2022-03-15 01:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0006_likecomment_likepost_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likecomment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='likepost',
            name='id',
        ),
        migrations.AlterField(
            model_name='likecomment',
            name='like_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='likepost',
            name='like_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
