# Generated by Django 4.0.2 on 2022-03-15 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('following', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('requestingAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followerRequest', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('author', 'requestingAuthor')},
            },
        ),
    ]
