# Generated by Django 4.0.2 on 2022-03-15 06:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('following', '0002_followrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followrequest',
            old_name='requestingAuthor',
            new_name='requesting_author',
        ),
        migrations.AlterUniqueTogether(
            name='followrequest',
            unique_together={('author', 'requesting_author')},
        ),
    ]
